feat(FOCUS-1570) added replenishable to product inventory
AbsoluteWebServices/magento2 pull request #111
Opened 2022-06-23 21:06 UTC by sara-yoffe

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-28 19:56 UTC, dmitry-kozachek requested changes

2022-06-28 19:56 UTC, dmitry-kozachek commented on packages/api-client/schema.graphql
> +  replenishable: Boolean
@sara-yoffe you added this field to the schema, but you also need to add it to the `focusInventory` query (packages/api-client/src/api/focusInventory/focusInventory.ts)

2022-06-29 13:57 UTC, sara-yoffe commented on packages/api-client/schema.graphql
> +  replenishable: Boolean
@dmitry-kozachek I had a feeling I was missing something. I updated it now.

2022-06-29 17:06 UTC, dmitry-kozachek approved these changes

2022-06-29 17:06 UTC, merged